components:
  schemas:
    GetMapCenterRs:
      type: object
      properties:
        origin:
          type: object
          properties:
            map_center_id:
              type: string
              example: 0d367ba3-a2e8-4380-86c3-ab7c0b7890c0
            search_map_center:
              type: object
              properties:
                longitude:
                  type: number
                  example: -74.0060
                latitude:
                  type: number
                  example: 40.7128
            sell_map_center:
              type: object
              properties:
                longitude:
                  type: number
                  example: -118.2437
                latitude:
                  type: number
                  example: 34.0522

    SaveMapCenterRq:
      type: object
      properties:
        longitude:
          type: number
          example: -74.0060
        latitude:
          type: number
          example: 40.7128
        type:
          type: string
          example: search

    SaveMapCenterRs:
      type: object
      properties:
        map_center_id:
          type: string
          example: 0d367ba3-a2e8-4380-86c3-ab7c0b7890c0
        search_map_center:
          type: object
          properties:
            longitude:
              type: number
              example: -74.0060
            latitude:
              type: number
              example: 40.7128
        sell_map_center:
          type: object
          properties:
            longitude:
              type: number
              example: -118.2437
            latitude:
              type: number
              example: 34.0522