components:
  schemas:
    AuthenticateUserRq:
      type: object
      properties:   
        user:
          type: object
          properties:
            pi_uid:
              type: string
              example: 0d367ba3-a2e8-4380-86c3-ab7c0b7890c0
            pi_username:
              type: string
              example: test_alias
            user_name:
              type: string
              example: Test Alias
          required:
            - pi_uid
      required:
        - user

    AuthenticateUserRs:
      type: object
      properties:
        user:
          type: object
          properties:
            _id:
              type: string
              example: 666bbae4a05bcc3d8dfab563
            pi_uid:
              type: string
              example: 0d367ba3-a2e8-4380-86c3-ab7c0b7890c0
            pi_username:
              type: string
              example: test_alias
            user_name:
              type: string
              example: Test Alias
            __v:
              type: integer
              example: 0
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjZiYmFlNGEwNWJjYzNkOGRmYWI1NjMiLCJpYXQiOjE3MTgzMzk0MDksImV4cCI6MTcyMDkzMTQwOX0.gFz-EdHoOqz3-AuFX5R4uGtruFaTMH8sTOXEX-3c7yw
      required:
        - user
        - token

    GetUserRs:
      type: object
      properties:
        user:
          type: object
          properties:
            _id:
              type: string
              example: 666bbae4a05bcc3d8dfab563
            pi_uid:
              type: string
              example: 0d367ba3-a2e8-4380-86c3-ab7c0b7890c0
            pi_username:
              type: string
              example: test_alias
            user_name:
              type: string
              example: Test Alias
            __v:
              type: integer
              example: 0    
      required:
        - user

    DeleteUserRs:
      type: object
      properties:
        message:
          type: string
          example: User deleted successfully.
        deletedData:
          type: object
          properties:
            user:
              type: object
              properties:
                _id:
                  type: string
                  example: 666bbae4a05bcc3d8dfab563
                pi_uid:
                  type: string
                  example: 0d367ba3-a2e8-4380-86c3-ab7c0b7890c0
                pi_username:
                  type: string
                  example: test_alias
                user_name:
                  type: string
                  example: Test Alias
                __v:
                  type: integer
                  example: 0
            sellers:
              type: array
              items:
                type: object
                properties:
                  seller_id:
                    type: string
                    example: 0d367ba3-a2e8-4380-86c3-ab7c0b7890c0
                  name:
                    type: string
                    example: Test Seller
                  description:
                    type: string
                    example: This is a sample seller description.
                  image:
                    type: string
                    example: http://example.com/image.jpg
                  address:
                    type: string
                    example: 1234 Test St, Test City, SC 12345
                  sale_items:
                    type: string
                    example: Test Item 1, Test Item 2
                  average_rating:
                    type: object
                    properties:
                      $numberDecimal:
                        type: string
                        example: 4.5
                    required:
                      - $numberDecimal
                  trust_meter_rating:
                    $ref: '/api/docs/enum/TrustMeterScale.yml#/components/schemas/TrustMeterScale'
                  sell_map_center:
                    type: object
                    properties:
                      type:
                        type: string
                        example: Point
                      coordinates:
                        type: array
                        items:
                          type: number
                        example: [-73.856077, 40.848447]
                    required:
                      - type
                      - coordinates
                  order_online_enabled_pref:
                    type: boolean
                    example: true
            userSetting:
              type: object
              properties:
                user_settings_id:
                  type: string
                  example: 0d367ba3-a2e8-4380-86c3-ab7c0b7890c0
                email:
                  type: string
                  example: test_user_preferences@example.com
                phone_number:
                  type: number
                  example: 123456789
                image:
                  type: string
                  example: https://example.com/image.jpg
                search_map_center:
                  type: object
                  properties:
                    type:
                      type: string
                      example: Point
                    coordinates:
                      type: array
                      items:
                        type: number
                      example: [-73.856077, 40.848447]
                  required:
                    - type
                    - coordinates